apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kube-vip.name" . }}-sa
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "kube-vip.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube-vip.name" . }}-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: [""]
    resources: ["services", "services/status", "nodes", "endpoints"]
    verbs: ["list","get","watch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["list", "get", "watch", "update", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "kube-vip.name" . }}-role-binding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "kube-vip.name" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "kube-vip.name" . }}-sa
  namespace: {{ .Release.Namespace }}
